# Generated by Django 3.1.2 on 2020-11-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Edition', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('Author', models.CharField(default='None', max_length=40)),
                ('Description', models.TextField(default='TYPE YOUR DESCRIPTION', null=True)),
            ],
        ),
    ]
