# Generated by Django 3.1.2 on 2020-11-26 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_auto_20201124_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='fine',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='issue',
            name='rdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
